apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polybot-dev-ingress
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
  - host: haitham-dev.fursa.click
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: polybot-dev
            port:
              number: 8443