
name : terraform and k8s 
on :
  push:
    branches:
      - feature/k8s_infra

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_ssh_key_name: my-key
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        run: |
          cd tf
          terraform init
          if terraform workspace list | grep -qw "us-east-1"; then
            echo "workspace exist"
          else 
            terraform workspace new us-east-1
          fi
          terraform workspace select us-east-1
          terraform apply -var-file region.us-east-1.tfvars -auto-approve

      - name: Get public IP from Terraform output
        id: tf_output
        run: |
          cd tf
          ip=$(terraform output -raw instance_public_ip 2>/dev/null | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n 1)
          echo "::notice::Got public IP: $ip"
          echo "ip=$ip" >> "$GITHUB_OUTPUT" 
      

Deploy:
    needs: terraform 
    uses: ./.github/workflows/terraform.yaml
    with:
      ip: ${{ needs.terraform.outputs.ip }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}




